[package]
name = "jet-math"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uint = "0.9"
thiserror = "1.0"
bytemuck = { version = "1.7", features = ["derive"] }
static_assertions = "1.1.0"
