[programs.devnet]
gem_bank = "DAAEGzczZTN83mz2WEg8NQQSVAaCKTViXvshUGGyjJyi"
gem_farm = "GohNJHF8oQnUpzdzS6qWBViJkg4Hv78CKWF8585KZW9V"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "solana-wallet/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

#[test]
#startup_wait = 100000

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./tests/programs/metaplex_token_metadata.so"